# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: Docs PR Preview

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, closed]
    paths:
      - "docs/**"
      - "README.md"
      - "pyproject.toml"
      - "uv.lock"
      - ".github/workflows/docs-preview-pr.yaml"

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  preview:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Set up Python
        if: github.event.action != 'closed'
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: "3.11"

      - name: Install uv
        if: github.event.action != 'closed'
        uses: astral-sh/setup-uv@38f3f104447c67c051c4a08e39b64a148898af3a # v4

      - name: Install doc dependencies
        if: github.event.action != 'closed'
        run: uv sync --group docs

      - name: Build documentation
        if: github.event.action != 'closed'
        run: uv run --group docs sphinx-build -W -b html docs docs/_build/html

      - name: Clean build artifacts
        if: github.event.action != 'closed'
        run: |
          find docs/_build -name .doctrees -prune -exec rm -rf {} \;
          find docs/_build -name .buildinfo -exec rm {} \;
          touch docs/_build/html/.nojekyll

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@ffa7509e91a3ec8dfc2e5536c4d5c1acdf7a6de9 # v1
        with:
          source-dir: ./docs/_build/html/
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto
